config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :alunos
  resources :emprestimos
  resources :livros
  root to: 'home#index'

  resources :livros do
    member do
      post 'emprestar'
    end
  end

resources :emprestimos do
  member do
    get 'generate_receipt', format: :pdf
  end
end

  
  get "up" => "rails/health#show", as: :rails_health_check

  get 'home/exportar_alunos_csv', to: 'home#exportar_alunos_csv', as: :exportar_alunos_csv, defaults: { format: 'csv' }
  
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    has_many :emprestimos
    has_many :emprestalivro

    validates :nome, presence: true
    validates :matricula, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/emprestimo.rb
# app/models/emprestimo.rb
class Emprestimo < ApplicationRecord
  belongs_to :livro
  belongs_to :aluno

  validates_presence_of :livro_id, :aluno_id
  def ativo?
    data_devolucao.nil?
  end
end

app/models/livro.rb
class Livro < ApplicationRecord
    has_many :emprestimos
    has_many :emprestalivro


    validates :titulo, presence: true
    validates :autor, presence: true

    def emprestado?
        emprestimos.any?
      end
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: %i[ show edit update destroy ]

  # GET /alunos or /alunos.json
  def index
    @alunos = Aluno.all
    @alunos = @alunos.page(params[:page]).per(2)

  end

  # GET /alunos/1 or /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos or /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to aluno_url(@aluno), notice: "Aluno was successfully created." }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1 or /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to aluno_url(@aluno), notice: "Aluno was successfully updated." }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1 or /alunos/1.json
  def destroy
    @aluno.destroy!

    respond_to do |format|
      format.html { redirect_to alunos_url, notice: "Aluno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aluno_params
      params.require(:aluno).permit(:nome, :matricula)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
  end
  

app/controllers/emprestimos_controller.rb
# app/controllers/emprestimos_controller.rb
class EmprestimosController < ApplicationController
  def new
    @emprestimo = Emprestimo.new
  end

  def index
    @emprestimos = Emprestimo.all 
    @emprestimo = Emprestimo.new 
  
    @emprestimos = @emprestimos.page(params[:page]).per(2)
  end

  def create
    @emprestimo = Emprestimo.new(emprestimo_params)

    respond_to do |format|
      if @emprestimo.save
        format.html { redirect_to @emprestimo, notice: 'Empréstimo criado com sucesso.' }
        format.json { render :show, status: :created, location: @emprestimo }
      else
        format.html { render :new }
        format.json { render json: @emprestimo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @emprestimo = Emprestimo.find(params[:id])  # Certifique-se de adicionar esta linha para carregar o empréstimo correto
    @emprestimo.destroy
    respond_to do |format|
      format.html { redirect_to emprestimos_url, notice: 'Empréstimo foi excluído com sucesso.' }
      format.json { head :no_content }
    end
  end
  
  # ... outras ações ...

  def generate_receipt
    @emprestimo = Emprestimo.find(params[:id])

    respond_to do |format|
      format.pdf do
        pdf = EmprestimoPdf.new(@emprestimo)
        send_data pdf.render, filename: 'recibo_emprestimo.pdf', type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  private

  def emprestimo_params
    params.require(:emprestimo).permit(:livro_id, :aluno_id, :data_emprestimo, :data_devolucao)
  end
end

app/controllers/home_controller.rb
require 'csv'

class HomeController < ApplicationController
  def index
  end

  def exportar_alunos_csv
    @alunos = Aluno.all

    respond_to do |format|
      format.csv do
        send_data alunos_to_csv, filename: "alunos.csv", type: 'text/csv', disposition: 'attachment'
      end
    end
  end

  private

  def alunos_to_csv
    CSV.generate(headers: true) do |csv|
      csv << ['ID', 'Nome', 'Matrícula']

      @alunos.each do |aluno|
        csv << [aluno.id, aluno.nome, aluno.matricula]
      end
    end
  end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: %i[ show edit update destroy ]

  # GET /livros or /livros.json
  def index
    @livros = Livro.all
    @livros = @livros.page(params[:page]).per(2)

  end

  # GET /livros/1 or /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros or /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully created." }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1 or /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully updated." }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1 or /livros/1.json
  def destroy
    @livro.destroy!

    respond_to do |format|
      format.html { redirect_to livros_url, notice: "Livro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def emprestar
    livro = Livro.find(params[:id])
    
    # Verifique se o livro não está emprestado antes de permitir o empréstimo
    if livro.emprestado?
      flash[:alert] = "Este livro já está emprestado."
    else
      Emprestimo.create(livro: livro, aluno: current_user, data_emprestimo: Time.now)
      flash[:notice] = "Livro emprestado com sucesso."
    end

    redirect_to livros_path
  end

  private
    def set_livro
      @livro = Livro.find(params[:id])
    end

    def livro_params
      params.require(:livro).permit(:titulo, :autor)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresta_helper.rb
module EmprestaHelper
end

app/helpers/empresta_livro_helper.rb
module EmprestaLivroHelper
end

app/helpers/emprestimos_helper.rb
module EmprestimosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/alunos/_aluno.html.erb
<div id="<%= dom_id aluno %>">
  <p>
    <strong>Nome:</strong>
    <%= aluno.nome %>
  </p>

  <p>
    <strong>Matricula:</strong>
    <%= aluno.matricula %>
  </p>

</div>

app/views/alunos/_form.html.erb
<%= form_with(model: aluno) do |form| %>
  <% if aluno.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
        <% aluno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="ms-2 w-100">

  <div class="">
    <%= form.label :nome, style: "display: block", class: "form-label" %>
    <%= form.text_field :nome, class: "form-control" %>
  </div>

  <div>
    <%= form.label :matricula, style: "display: block", class: "form-label" %>
    <%= form.text_field :matricula, class: "form-control" %>
  </div>

  <div class="mt-2">
    <%= form.submit 'Salvar', class: 'btn btn-primary' %>

  </div>
</div>
<% end %>

app/views/alunos/edit.html.erb
<div class="d-flex flex-column align-items-center justify-content-center h-25 ms-2">

<h1>Editar aluno</h1>

<%= render "form", aluno: @aluno %>

<br>

<div>
  <%= link_to "Exibir aluno", @aluno %> |
  <%= link_to "Voltar", alunos_path %>
</div>
</div>

app/views/alunos/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark w-100 text-white p-3 mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://localhost:5001">Biblioteca</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link " aria-current="page" href="http://localhost:5001">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="http://localhost:5001/alunos">Alunos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:5001/livros">Livros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:5001/emprestimos">Emprestimo de livro</a>
        </li>
        <li class="nav-item">
          <%=  link_to 'Sair', destroy_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Exportar Alunos para CSV', exportar_alunos_csv_path, class: 'btn-exportar-csv nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class='d-flex flex-column align-items-center'>
<h1>Alunos</h1>

<div id="alunos" class="" >
  <% @alunos.each do |aluno| %>
    <div class="ms-1 card  p-3 mb-2">
      <p><strong>Nome:</strong>
      <%= aluno.nome %>
      </p>

      <p><strong>Matrícula:</strong>
      <%= aluno.matricula %>
      </p>
    <p>
      <%= link_to "Exibir aluno", aluno, class:'btn btn-primary'%>
    </p>
    </div>

  <% end %>
</div>

<%= link_to "Novo aluno", new_aluno_path, class: "btn btn-success" %>

<div class="pagination">
              <%= paginate @alunos %>
          </div>
</div>

app/views/alunos/new.html.erb
<div class="ms-2 d-flex align-items-center justify-content-center flex-column h-50">
  <h1>Novo aluno</h1>

  <%= render "form", aluno: @aluno %>

  <br>

  <div>
    <%= link_to "Voltar para alunos", alunos_path %>
  </div>
</div>

app/views/alunos/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex flex-column align-items-center justify-content-center w-100 h-25 fs-4">
<div class="card p-4">
<%= render @aluno %>

  <%= link_to "Editar aluno", edit_aluno_path(@aluno), class: "btn btn-primary mb-1" %> 
  <%= link_to "Voltar", alunos_path, class: "btn btn-secondary" %>

  <%= button_to "Excluir", @aluno, method: :delete, class:"btn btn-danger" %>
</div>
</div> 

app/views/emprestimos/_emprestimo.html.erb
<div id="<%= dom_id emprestimo %>">
  <p>
    <strong>Aluno:</strong>
    <%= emprestimo.aluno_id %>
  </p>

  <p>
    <strong>Livro:</strong>
    <%= emprestimo.livro_id %>
  </p>

  <p>
    <strong>Data emprestimo:</strong>
    <%= emprestimo.data_emprestimo %>
  </p>

  <p>
    <strong>Data devolucao:</strong>
    <%= emprestimo.data_devolucao %>
  </p>

</div>

app/views/emprestimos/_form.html.erb
<%= form_with(model: emprestimo) do |form| %>
  <% if emprestimo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(emprestimo.errors.count, "error") %> prohibited this emprestimo from being saved:</h2>

      <ul>
        <% emprestimo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :aluno_id, style: "display: block" %>
    <%= form.text_field :aluno_id %>
  </div>

  <div>
    <%= form.label :livro_id, style: "display: block" %>
    <%= form.text_field :livro_id %>
  </div>

  <div>
    <%= form.label :data_emprestimo, style: "display: block" %>
    <%= form.date_field :data_emprestimo %>
  </div>

  <div>
    <%= form.label :data_devolucao, style: "display: block" %>
    <%= form.date_field :data_devolucao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/emprestimos/edit.html.erb
<h1>Editing emprestimo</h1>

<%= render "form", emprestimo: @emprestimo %>

<br>

<div>
  <%= link_to "Show this emprestimo", @emprestimo %> |
  <%= link_to "Back to emprestimos", emprestimos_path %>
</div>

app/views/emprestimos/index.html.erb
<!-- app/views/emprestimos/new.html.erb -->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark w-100 text-white p-3 mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://localhost:5001">Biblioteca</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="http://localhost:5001">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="http://localhost:5001/alunos">Alunos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:5001/livros">Livros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:5001/emprestimos">Emprestimo de livro</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Sair', destroy_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Exportar Alunos para CSV', exportar_alunos_csv_path, class: 'btn-exportar-csv nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row mt-5">
    <div class="col-md-6 position-fixed  mt-5 card w-25">
      <h1>Novo Empréstimo</h1>

      <%= form_with(model: @emprestimo, local: true, data: { controller: "turbo-stream" }) do |form| %>
        <div class="mb-3">
          <%= form.label :livro_id, class: "form-label" %>
          <%= form.collection_select :livro_id, Livro.all, :id, :titulo, prompt: 'Selecione um livro', class: 'form-select' %>
        </div>

        <div class="mb-3">
          <%= form.label :aluno_id, class: "form-label" %>
          <%= form.collection_select :aluno_id, Aluno.all, :id, :nome, prompt: 'Selecione um aluno', class: 'form-select' %>
        </div>

        <div class="mb-3">
          <%= form.submit 'Criar Empréstimo', class: 'btn btn-primary' %>
        </div>
      <% end %>

      <a href="http://localhost:5001" class="btn btn-secondary w-25">Voltar</a>
    </div>

    <!-- Seção de livros emprestados -->
    <div class="col-md-6 float-end w-100">
      <% if @emprestimos.present? %>
        <div id="livros-emprestados" class="float-end me-5 ">
          <h2 class="mb-2">Livros Emprestados</h2>
          <% @emprestimos.each do |emprestimo| %>
            <div class="emprestimo mb-4 card p-2 bg-info"style="--bs-bg-opacity: .2;">
              <p><strong>Aluno:</strong> <%= emprestimo.aluno.nome %></p>
              <p><strong>Livro:</strong> <%= emprestimo.livro.titulo %></p>

              <%= link_to 'Download Recibo', generate_receipt_emprestimo_path(emprestimo, format: :pdf), class: 'btn btn-secondary me-2 w-75' %>
              <%= button_to 'Excluir Empréstimo', emprestimo, method: :delete, data: { confirm: 'Tem certeza que deseja excluir este empréstimo?' }, class: 'btn btn-danger w-75 mt-2' %>
            </div>
          <% end %>
          <div class="pagination">
              <%= paginate @emprestimos %>
          </div>
        </div>
      <% else %>
        <p>Nenhum livro emprestado no momento.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/emprestimos/new.html.erb
<h1>New emprestimo</h1>

<%= render "form", emprestimo: @emprestimo %>

<br>

<div>
  <%= link_to "Back to emprestimos", emprestimos_path %>
</div>

app/views/emprestimos/show.html.erb
<h1>realizado<h1>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<div class="overflow-hidden">
<div class="d-flex flex-column ">

<% if user_signed_in? %>
  <!-- Se o usuário estiver logado, exiba as seções de livros e empréstimos -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark w-100 text-white p-3 mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://localhost:5001">Biblioteca</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link " aria-current="page" href="http://localhost:5001">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="http://localhost:5001/alunos">Alunos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:5001/livros">Livros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:5001/emprestimos">Emprestimo de livro</a>
        </li>
        <li class="nav-item">
          <%=  link_to 'Sair', destroy_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Exportar Alunos para CSV', exportar_alunos_csv_path, class: 'btn-exportar-csv nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid mt-4">
  <div class="row">
    <div class="col-md-6 d-flex align-items-center">
      <h1 class="w-75 ms-5">Bem-vindo ao sistema de Biblioteca da Universidade XXXXXXXXXXX</h1>
    </div>
    <div class="col-md-6">
      <%= image_tag asset_path('biblioteca.jpg'), class: "img-fluid rounded" %>
    </div>
  </div>
</div>


<% else %>
  <!-- Se o usuário não estiver logado, exiba o link para fazer o login -->
  <%= link_to 'Fazer Login', new_user_session_path %>
<% end %>
  

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Adicione isso ao head do seu layout -->
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js' %>

    <title class="">Biblioteca</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/livros/_form.html.erb
<%= form_with(model: livro) do |form| %>
  <% if livro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
        <% livro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-100">
    <%= form.label :titulo, style: "display: block",class: "form-label" %>
    <%= form.text_field :titulo, class: "form-control" %>
  </div>

  <div>
    <%= form.label :autor, style: "display: block",class: "form-label" %>
    <%= form.text_field :autor,class: "form-control" %>
  </div>

  <div class="mt-2">
    <%= form.submit "Salvar", class:"btn btn-primary " %>
  </div>
<% end %>

app/views/livros/_livro.html.erb
<div id="<%= dom_id livro %>">
  <p>
    <strong>Titulo:</strong>
    <%= livro.titulo %>
  </p>

  <p>
    <strong>Autor:</strong>
    <%= livro.autor %>
  </p>

</div>

app/views/livros/edit.html.erb
<div class="d-flex flex-column align-items-center justify-content-center h-25 ms-2">

<h1>Editar livro</h1>

<%= render "form", livro: @livro %>

<br>

<div>
  <%= link_to "Exibir livro", @livro %> |
  <%= link_to "Voltar", livros_path %>
</div>
</div>

app/views/livros/index.html.erb
<!-- app/views/livros/index.html.erb -->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark w-100 text-white p-3 mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://localhost:5001">Biblioteca</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link " aria-current="page" href="http://localhost:5001">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="http://localhost:5001/alunos">Alunos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:5001/livros">Livros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:5001/emprestimos">Emprestimo de livro</a>
        </li>
        <li class="nav-item">
          <%=  link_to 'Sair', destroy_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Exportar Alunos para CSV', exportar_alunos_csv_path, class: 'btn-exportar-csv nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class='d-flex flex-column align-items-center'>
<h1>Livros</h1>

<div id="livros">
  <% @livros.each do |livro| %>


    <div class="ms-1 card  p-3 mb-2">
      <p><strong>Título:</strong>
      <%= livro.titulo %>
      </p>

      <p><strong>Autor:</strong>
      <%= livro.autor %>
      </p>

    <% if livro.emprestado? %>
        <p class="status-emprestimo">Emprestado</p>
  <% end %>
      
    <p>
      <%= link_to "Exibir Livro", livro, class:'btn btn-primary'%>
    </p>
    
</div>
     <% end %>
</div>

<div class="pagination">
              <%= paginate @livros %>
          </div>

    
<%= link_to 'Novo livro', new_livro_path, class:"btn btn-success" %>
</div>

app/views/livros/new.html.erb
<div class="ms-2 d-flex align-items-center justify-content-center flex-column h-25">

<h1>Novo livro</h1>

<%= render "form", livro: @livro %>

<br>

<div class="mt-2">
  <%= link_to "Voltar para livros", livros_path %>
</div>
</div>

app/views/livros/show.html.erb
<p style="color: green"><%= notice %></p>



<div class="d-flex flex-column align-items-center justify-content-center w-100 h-25 fs-4">
<div class="card p-4">
<%= render @livro %>

  <%= link_to "Editar", edit_livro_path(@livro), class: "btn btn-primary mb-1" %> 
  <%= link_to "Voltar", livros_path, class: "btn btn-secondary" %>

  <%= button_to "Excluir", @livro, method: :delete, class: "btn btn-danger" %>
</div>
</div> 